# Generated by Django 3.1.7 on 2021-02-20 00:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('driver_age', models.IntegerField()),
                ('driver_gender', models.CharField(max_length=255)),
                ('driver_employment', models.CharField(max_length=255)),
                ('driver_marital', models.CharField(max_length=255)),
                ('driver_location', models.CharField(max_length=255)),
                ('vehicle_age', models.IntegerField()),
                ('vehicle_model', models.CharField(max_length=255)),
                ('insurance_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insurance_claims', models.IntegerField()),
                ('insurance_losses', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
